# 1. Never Expose the ports in production except 80 & 443 (default port)
# 2. Use the docker networks

services:
  # Database Service
  mongodb:
    image: mongo:latest
    container_name: dev_mongodb
    networks:
      - dev_net
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s # run every 10s
      retries: 5 # fail 5 times before marking unhealthy
      timeout: 5s # each attempt must finish within 5s
    restart: unless-stopped

  # Backend Service
  backend:
    build:
      context: ./apps/backend
    container_name: backend
    networks:
      - dev_net
    env_file:
      - ./apps/backend/.env
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "-q", "http://localhost:8001/api/v1/health"]
      retries: 3
      interval: 10s
      timeout: 2s
    restart: unless-stopped
    # It will deploy the 4 replicas of backend service & remove the the container_name because it will
    # auto name it. (backend-1, backend-2, etc...)
    # deploy:
    #   replicas: 4

  # Frontend Service (Main)
  frontend:
    build:
      context: ./apps/frontend
    container_name: frontend
    networks:
      - dev_net
    env_file:
      - ./apps/frontend/.env
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:80"
    restart: unless-stopped

  # Frontend - Admin panel
  frontend_admin:
    build:
      context: ./apps/frontend_admin
    container_name: frontend_admin
    networks:
      - dev_net
    env_file:
      - ./apps/frontend_admin/.env
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3001:80"
    restart: unless-stopped

# Networks & Volumes
networks:
  dev_net:
    driver: bridge

volumes:
  mongodb_data:
    name: dev_mongodb_data
