# 1. Never Expose the ports in production except 80 & 443 (default port)
# 2. Use the docker networks

services:
  # Database Service
  mongodb:
    image: mongo:latest
    container_name: prod_mongodb
    networks:
      - prod_net
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      timeout: 5s
    restart: unless-stopped

  # Backend Service
  backend:
    image: mern-app-backend:latest
    build: 
      context: ./apps/backend
      dockerfile: Dockerfile
    networks:
      - prod_net
    env_file:
      - ./apps/backend/.env
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "-q", "http://localhost:8001/api/v1/health"]
      retries: 3
      interval: 10s
      timeout: 2s
    restart: unless-stopped
    deploy:
      replicas: 3

  # Frontend Service (Main)
  frontend:
    image: mern-app-frontend:latest
    build: 
      context: ./apps/frontend
      dockerfile: Dockerfile
    networks:
      - prod_net
      - mern-project
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-router.rule=Host(`jugalmahida.localhost`)"
      - "traefik.http.services.my-router.loadbalancer.server.port=80"
      - "traefik.docker.network=mern-project"
      # - 'traefik.http.routers.my-router.entrypoints=websecure'
      # - 'traefik.http.routers.my-router.tls=true'
      # - 'traefik.http.routers.my-router.tls.certresolver=cert-resolver'
    env_file:
      - ./apps/frontend/.env
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: 3

  # Frontend - Admin panel
  frontend_admin:
    image: mern-app-adminpanel:latest
    build: 
      context: ./apps/frontend_admin
      dockerfile: Dockerfile
    networks:
      - prod_net
      - mern-project
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-admin-router.rule=Host(`admin.jugalmahida.localhost`)"
      - "traefik.http.services.my-admin-router.loadbalancer.server.port=80"
      - "traefik.docker.network=mern-project"
      # - 'traefik.http.routers.my-router.entrypoints=websecure'
      # - 'traefik.http.routers.my-router.tls=true'
      # - 'traefik.http.routers.my-router.tls.certresolver=cert-resolver'
    env_file:
      - ./apps/frontend_admin/.env
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: 2

# Networks & Volumes
networks:
  prod_net:
    driver: bridge
  mern-project:
    external: true

volumes:
  mongodb_data:
    name: prod_mongodb_data
